import { Router } from '@/types/router';
import { Device, DeviceType, ConnectionType } from '@/types/device';
import { NetworkStatus, BandwidthData, NetworkEvent } from '@/types/network';

export const mockRouters: Router[] = [
  {
    id: 'router-1',
    name: 'Main Gateway',
    model: 'Huawei HG8245W5',
    ipAddress: '192.168.1.1',
    macAddress: '00:1A:2B:3C:4D:5E',
    status: 'online',
    firmwareVersion: 'V5R019C10S150',
    cpuUsage: 45,
    memoryUsage: 62,
    signalStrength: 85,
    ssid: 'HomeNetwork_2.4G',
    ssid5g: 'HomeNetwork_5G',
    connectedClients: 12,
    uptime: 1440,
    location: 'Living Room',
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'router-2',
    name: 'Office Router',
    model: 'D-Link DWR-X1852E',
    ipAddress: '192.168.1.2',
    macAddress: '00:1A:2B:3C:4D:5F',
    status: 'online',
    firmwareVersion: '1.04B02',
    cpuUsage: 32,
    memoryUsage: 48,
    signalStrength: 90,
    ssid: 'OfficeNetwork',
    connectedClients: 8,
    uptime: 2880,
    location: 'Office',
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'router-3',
    name: 'Bedroom Extender',
    model: 'Tenda N301',
    ipAddress: '192.168.1.3',
    macAddress: '00:1A:2B:3C:4D:60',
    status: 'warning',
    firmwareVersion: 'V12.0.0.1',
    cpuUsage: 78,
    memoryUsage: 71,
    signalStrength: 65,
    ssid: 'Bedroom_WiFi',
    connectedClients: 4,
    uptime: 720,
    location: 'Bedroom',
    lastSeen: new Date().toISOString(),
  },
  {
    id: 'router-4',
    name: 'Garden Router',
    model: 'Tenda F3',
    ipAddress: '192.168.1.4',
    macAddress: '00:1A:2B:3C:4D:61',
    status: 'offline',
    firmwareVersion: 'V5.0.1',
    cpuUsage: 0,
    memoryUsage: 0,
    signalStrength: 0,
    ssid: 'GardenWiFi',
    connectedClients: 0,
    uptime: 0,
    location: 'Garden',
    lastSeen: new Date(Date.now() - 3600000).toISOString(),
  },
];

export const mockDevices: Device[] = [
  {
    id: 'device-1',
    name: 'iPhone 15 Pro',
    hostname: 'iphone-alijah',
    macAddress: 'AA:BB:CC:DD:EE:01',
    ipAddress: '192.168.1.101',
    deviceType: 'smartphone',
    connectionType: 'wifi',
    routerId: 'router-1',
    routerName: 'Main Gateway',
    status: 'online',
    bandwidthIn: 1024000,
    bandwidthOut: 512000,
    firstSeen: new Date(Date.now() - 86400000).toISOString(),
    lastSeen: new Date().toISOString(),
    vendor: 'Apple',
    isBlocked: false,
    signalStrength: 85,
  },
  {
    id: 'device-2',
    name: 'MacBook Pro',
    hostname: 'macbook-work',
    macAddress: 'AA:BB:CC:DD:EE:02',
    ipAddress: '192.168.1.102',
    deviceType: 'laptop',
    connectionType: 'wifi',
    routerId: 'router-2',
    routerName: 'Office Router',
    status: 'online',
    bandwidthIn: 2048000,
    bandwidthOut: 1024000,
    firstSeen: new Date(Date.now() - 172800000).toISOString(),
    lastSeen: new Date().toISOString(),
    vendor: 'Apple',
    isBlocked: false,
    signalStrength: 92,
  },
  {
    id: 'device-3',
    name: 'Desktop PC',
    hostname: 'gaming-rig',
    macAddress: 'AA:BB:CC:DD:EE:03',
    ipAddress: '192.168.1.103',
    deviceType: 'desktop',
    connectionType: 'ethernet',
    routerId: 'router-1',
    routerName: 'Main Gateway',
    status: 'online',
    bandwidthIn: 5120000,
    bandwidthOut: 1024000,
    firstSeen: new Date(Date.now() - 259200000).toISOString(),
    lastSeen: new Date().toISOString(),
    vendor: 'Custom Build',
    isBlocked: false,
  },
  {
    id: 'device-4',
    name: 'Smart TV',
    hostname: 'samsung-tv',
    macAddress: 'AA:BB:CC:DD:EE:04',
    ipAddress: '192.168.1.104',
    deviceType: 'smart_tv',
    connectionType: 'wifi',
    routerId: 'router-1',
    routerName: 'Main Gateway',
    status: 'online',
    bandwidthIn: 4096000,
    bandwidthOut: 256000,
    firstSeen: new Date(Date.now() - 345600000).toISOString(),
    lastSeen: new Date().toISOString(),
    vendor: 'Samsung',
    isBlocked: false,
    signalStrength: 70,
  },
  {
    id: 'device-5',
    name: 'iPad Air',
    hostname: 'ipad-tablet',
    macAddress: 'AA:BB:CC:DD:EE:05',
    ipAddress: '192.168.1.105',
    deviceType: 'tablet',
    connectionType: 'wifi',
    routerId: 'router-3',
    routerName: 'Bedroom Extender',
    status: 'online',
    bandwidthIn: 512000,
    bandwidthOut: 256000,
    firstSeen: new Date(Date.now() - 432000000).toISOString(),
    lastSeen: new Date().toISOString(),
    vendor: 'Apple',
    isBlocked: false,
    signalStrength: 60,
  },
  {
    id: 'device-6',
    name: 'Security Cam 1',
    hostname: 'camera-front',
    macAddress: 'AA:BB:CC:DD:EE:06',
    ipAddress: '192.168.1.106',
    deviceType: 'camera',
    connectionType: 'wifi',
    routerId: 'router-1',
    routerName: 'Main Gateway',
    status: 'online',
    bandwidthIn: 768000,
    bandwidthOut: 128000,
    firstSeen: new Date(Date.now() - 518400000).toISOString(),
    lastSeen: new Date().toISOString(),
    vendor: 'Hikvision',
    isBlocked: false,
    signalStrength: 75,
  },
  {
    id: 'device-7',
    name: 'Smart Printer',
    hostname: 'printer-epson',
    macAddress: 'AA:BB:CC:DD:EE:07',
    ipAddress: '192.168.1.107',
    deviceType: 'printer',
    connectionType: 'wifi',
    routerId: 'router-2',
    routerName: 'Office Router',
    status: 'offline',
    bandwidthIn: 0,
    bandwidthOut: 0,
    firstSeen: new Date(Date.now() - 604800000).toISOString(),
    lastSeen: new Date(Date.now() - 3600000).toISOString(),
    vendor: 'Epson',
    isBlocked: false,
    signalStrength: 0,
  },
  {
    id: 'device-8',
    name: 'Smart Thermostat',
    hostname: 'nest-thermostat',
    macAddress: 'AA:BB:CC:DD:EE:08',
    ipAddress: '192.168.1.108',
    deviceType: 'iot',
    connectionType: 'wifi',
    routerId: 'router-1',
    routerName: 'Main Gateway',
    status: 'online',
    bandwidthIn: 64000,
    bandwidthOut: 64000,
    firstSeen: new Date(Date.now() - 691200000).toISOString(),
    lastSeen: new Date().toISOString(),
    vendor: 'Nest',
    isBlocked: false,
    signalStrength: 80,
  },
  {
    id: 'device-9',
    name: 'Unknown Device',
    hostname: 'unknown-host',
    macAddress: 'AA:BB:CC:DD:EE:09',
    ipAddress: '192.168.1.109',
    deviceType: 'other',
    connectionType: 'wifi',
    routerId: 'router-1',
    routerName: 'Main Gateway',
    status: 'blocked',
    bandwidthIn: 0,
    bandwidthOut: 0,
    firstSeen: new Date(Date.now() - 3600000).toISOString(),
    lastSeen: new Date().toISOString(),
    vendor: 'Unknown',
    isBlocked: true,
    signalStrength: 45,
  },
];

export const mockNetworkStatus: NetworkStatus = {
  status: 'online',
  wanIp: '203.0.113.45',
  gateway: '192.168.1.1',
  dns: ['8.8.8.8', '8.8.4.4'],
  internetSpeed: {
    download: 95.5,
    upload: 45.2,
    ping: 12,
  },
  totalBandwidth: {
    download: 1024 * 1024 * 1024 * 150,
    upload: 1024 * 1024 * 1024 * 50,
  },
  activeDevices: 7,
  totalDevices: 9,
  activeRouters: 3,
  totalRouters: 4,
};

export const generateBandwidthHistory = (): BandwidthData[] => {
  const data: BandwidthData[] = [];
  const now = Date.now();
  
  for (let i = 24; i >= 0; i--) {
    const baseDownload = 5 * 1024 * 1024;
    const baseUpload = 2 * 1024 * 1024;
    const randomVariation = () => Math.random() * 0.5 + 0.5;
    
    data.push({
      timestamp: new Date(now - i * 3600000).toISOString(),
      download: baseDownload * randomVariation(),
      upload: baseUpload * randomVariation(),
    });
  }
  
  return data;
};

export const mockNetworkEvents: NetworkEvent[] = [
  {
    id: 'event-1',
    timestamp: new Date(Date.now() - 120000).toISOString(),
    type: 'bandwidth_spike',
    severity: 'warning',
    message: 'High bandwidth usage detected on Main Gateway',
    details: { routerId: 'router-1', bandwidth: 45.5 },
  },
  {
    id: 'event-2',
    timestamp: new Date(Date.now() - 300000).toISOString(),
    type: 'device_connected',
    severity: 'info',
    message: 'iPhone 15 Pro connected to Tenda N301',
    details: { deviceId: 'device-1', routerId: 'router-3' },
  },
  {
    id: 'event-3',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    type: 'router_offline',
    severity: 'error',
    message: 'Garden Router (Tenda F3) went offline',
    details: { routerId: 'router-4' },
  },
  {
    id: 'event-4',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    type: 'device_disconnected',
    severity: 'info',
    message: 'Smart Printer disconnected from network',
    details: { deviceId: 'device-7' },
  },
  {
    id: 'event-5',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    type: 'security_alert',
    severity: 'warning',
    message: 'Suspicious device blocked: Unknown Device',
    details: { deviceId: 'device-9', macAddress: 'AA:BB:CC:DD:EE:09' },
  },
];
